"""Attach hand labels to golden candidates -> eval/golden_set.jsonl.

Labels were assigned by reading each message against the 9-intent taxonomy in
config.INTENTS and an escalation policy mirroring the agent's (abuse, legal/
deceased, compromised/unauthorized access, billing disputes/refunds on paid
plans, repeated unresolved troubleshooting escalate; routine factual/issues do
not). This file encodes the hand-set labels; provenance for every label is the
reviewer's reading of the raw message in golden_candidates.jsonl.
"""
from __future__ import annotations

import json

# id -> (gold_intent, gold_escalate, gold_escalation_reason)
GOLD: dict[str, tuple[str, bool, str]] = {
    # ---- account_access ----
    "976812": ("account_access", False, "routine password reset guidance"),
    "1909924": ("billing_subscription", False, "student plan verification issue"),
    "2806032": ("account_access", False, "password/email recovery on daughter's account"),
    "2704345": ("billing_subscription", False, "family plan status not recognized"),
    "1969654": ("billing_subscription", False, "locked accounts blocking family join"),
    "2623495": ("account_access", False, "email already in use during signup"),
    "1056943": ("account_access", True, "email address changed without authorization - potential compromise"),
    "2038953": ("account_access", False, "lost login for one of two accounts"),
    "2424860": ("account_access", False, "missing username/email/password"),
    "32483": ("account_access", False, "can't log in after Facebook deactivation"),
    "1801240": ("account_admin", False, "moved country; region/locale lock"),
    "1031954": ("account_access", True, "someone else controlling account via Spotify Connect - unauthorized access"),
    "2751293": ("account_access", False, "logged out and cannot sign back in"),
    "720774": ("account_access", False, "locked out, asking who to contact"),
    "492388": ("account_access", False, "bundle activation/login confusion"),
    "1026785": ("account_access", False, "cannot log in, requesting contact"),
    "2334619": ("billing_subscription", False, "gift card premium not applied"),
    "466037": ("account_access", False, "forgot password; reset loop"),
    "160577": ("account_access", False, "two accounts on one email"),
    "1767691": ("account_access", True, "premium account hacked"),
    "2275517": ("account_access", True, "playlists deleted + unknown music - possible account takeover"),
    "2428800": ("billing_subscription", False, "forgot login; wants to upgrade to family"),
    "2470248": ("account_access", True, "account hacked - playlists not created by user, unknown devices"),
    # ---- account_admin ----
    "461472": ("other_offtopic", False, "vague music recommendation request"),
    "1302813": ("account_admin", False, "duplicate accounts"),
    "1785648": ("account_admin", False, "change country via web player"),
    "2708572": ("account_admin", False, "artist page setup"),
    "2934023": ("content_library", False, "album/artist page mismatch"),
    "1546458": ("feature_request_feedback", False, "hyperlink/character counter limit complaint"),
    "95840": ("content_library", False, "multiple album versions on artist"),
    "2848340": ("content_library", False, "playlist proposes unplayable tracks in region"),
    "1933386": ("account_admin", False, "accounts share email; artist profile mix-up"),
    "249722": ("account_admin", False, "artist web upload failing"),
    "573763": ("content_library", False, "track title contains artist name"),
    "499236": ("content_library", False, "live versions replacing album tracks"),
    "1773082": ("feature_request_feedback", False, "want new releases from followed artists"),
    "2407031": ("content_library", False, "finding released music on artist page"),
    "2389822": ("feature_request_feedback", False, "change username request"),
    "1908036": ("feature_request_feedback", False, "block artists request"),
    "1643548": ("feature_request_feedback", False, "release notifications for followed artists"),
    "1781572": ("content_library", False, "can't play songs from specific artists"),
    "1552448": ("device_integration", False, "Google Assistant voice playback launches artist page only"),
    "189317": ("account_access", True, "account email changed without user request - compromise"),
    "912213": ("account_admin", False, "share shows internal id instead of username"),
    "994547": ("content_library", False, "correct artist attribution for an album"),
    "315130": ("account_admin", False, "songs moved to a different profile"),
    # ---- billing_subscription ----
    "1208834": ("billing_subscription", True, "student plan overcharged for months - billing dispute"),
    "1884173": ("billing_subscription", False, "premium status showing free"),
    "2051672": ("billing_subscription", False, "student plan renewal question"),
    "173641": ("billing_subscription", False, "promo purchase confirmation"),
    "2037114": ("billing_subscription", True, "student discount not applied; full amount charged"),
    "1809146": ("billing_subscription", True, "unrecognized Spotify charges on card"),
    "450868": ("billing_subscription", True, "charged 9.99 instead of student 4.99"),
    "910860": ("billing_subscription", True, "paid 1yr premium but account free - refund/policy"),
    "2272789": ("account_admin", False, "country change for family plan"),
    "500934": ("billing_subscription", False, "yearly plan still shows monthly charge"),
    "6495": ("billing_subscription", False, "bank payment not recognized"),
    "1962213": ("billing_subscription", True, "billing for deceased partner's account"),
    "573202": ("billing_subscription", False, "premium paid via phone credit not applied"),
    "2206070": ("billing_subscription", False, "premium repurchase not applied"),
    "2641111": ("account_access", True, "someone bought family pack on account - unauthorized"),
    "1551501": ("billing_subscription", False, "family members not showing premium"),
    "2077608": ("billing_subscription", True, "refund request"),
    "840732": ("account_admin", False, "business/brand account creation"),
    "1506694": ("technical_issue", False, "offline tracks lost + SD card stuck"),
    "708840": ("billing_subscription", False, "pro-rated refund question"),
    "1850802": ("billing_subscription", False, "promo expiry / reconciliation"),
    "1982945": ("technical_issue", False, "multiple issues + broken contact form"),
    "1963919": ("billing_subscription", False, "payment failed but card valid"),
    # ---- mostly closing/misc buckets (heuristic noise; relabelled by hand) ----
    "1909997": ("technical_issue", False, "lock-screen controls broken after update"),
    "2552610": ("device_integration", False, "notifications pause playback"),
    "1644196": ("feature_request_feedback", False, "iPhone X layout complaint"),
    "1335498": ("closing_acknowledgement", False, "thanks"),
    "38969": ("content_library", False, "track mislabeled"),
    "1727309": ("closing_acknowledgement", False, "thanks for fast help"),
    "2866588": ("closing_acknowledgement", False, "asking DM response time"),
    "2033918": ("closing_acknowledgement", False, "issue resolved"),
    "16203": ("content_library", False, "request to restore a band"),
    "1836163": ("billing_subscription", False, "trial not applied to account"),
    "2762998": ("closing_acknowledgement", False, "long wait complaint"),
    "2610833": ("technical_issue", False, "version difference question (FI)"),
    "1620806": ("closing_acknowledgement", False, "nudge to reply to DM"),
    "2866629": ("other_offtopic", False, "concert presale question - out of scope"),
    "353702": ("feature_request_feedback", False, "prefers old behavior"),
    "1002344": ("account_access", False, "citizens: cannot log in, DM status"),
    "718430": ("technical_issue", False, "web player stopped playing"),
    "2954691": ("technical_issue", False, "no text input in private messaging UI"),
    "485512": ("closing_acknowledgement", False, "thanks; will retry"),
    "2910977": ("closing_acknowledgement", False, "resolved by itself"),
    "350035": ("technical_issue", True, "unresolved after multiple troubleshooting attempts (still broken)"),
    "2810360": ("closing_acknowledgement", False, "praise for service"),
    "2038089": ("closing_acknowledgement", False, "praise for agent"),
    "102229": ("device_integration", False, "video loops streaming via AirPlay"),
    "413754": ("content_library", False, "album availability complaint"),
    "2891301": ("feature_request_feedback", False, "direct track share removed"),
    "1814532": ("account_access", True, "unknown songs/alarms on playlist - possible access"),
    "2907358": ("technical_issue", False, "search not working"),
    "2219850": ("content_library", False, "album listed under wrong band"),
    "2673236": ("content_library", False, "album not available (frustrated, not abusive)"),
    "379055": ("feature_request_feedback", False, "hide specific song in playlist"),
    "2195260": ("technical_issue", False, "songs need to be imported to play"),
    "1338951": ("content_library", False, "need album - not available"),
    "219037": ("content_library", False, "restore Discover Weekly playlists"),
    "2582040": ("content_library", False, "Time Capsule playlist behavior"),
    "123474": ("feature_request_feedback", False, "operator choice/options feature"),
    "2052778": ("feature_request_feedback", False, "full-screen album art"),
    "1532336": ("content_library", False, "duplicate artist profile from DistroKid"),
    "1471757": ("feature_request_feedback", False, "cannot share songs"),
    "2071776": ("feature_request_feedback", False, "library limit / save songs"),
    "1792816": ("feature_request_feedback", False, "update a playlist"),
    "1056939": ("content_library", False, "playlist filled with wrong-region songs"),
    "152233": ("feature_request_feedback", False, "search prioritizes own playlists"),
    "1582872": ("content_library", False, "album missing from app but on other platforms"),
    "2321781": ("feature_request_feedback", False, "lock-screen add/remove option"),
    "1197665": ("content_library", False, "region availability of Canadian band"),
    "1358459": ("other_offtopic", False, "Do you care? (no issue)"),
    "472538": ("technical_issue", False, "Windows 7 Chrome player fails"),
    "2293014": ("other_offtopic", False, "frustration about no replies; no issue stated"),
    "2302487": ("closing_acknowledgement", False, "fixed"),
    "497721": ("device_integration", False, "phone notifications while TV listening"),
    "2405258": ("feature_request_feedback", False, "floating video playback on macOS"),
    "2153126": ("technical_issue", False, "randomization + sort broken (Android)"),
    "2395948": ("device_integration", False, "mini-player question (Windows 10 desktop)"),
    "2125273": ("other_offtopic", False, "platform opinion chatter"),
    "1944166": ("feature_request_feedback", False, "wants phone support line"),
    "2517271": ("technical_issue", False, "media keys broken on macOS High Sierra"),
    "1611663": ("other_offtopic", False, "off-topic thread chatter"),
    "58933": ("technical_issue", False, "console errors; Firefox too"),
    "1684786": ("other_offtopic", False, "can add more items (no issue text)"),
    "1287756": ("content_library", False, "can't watch programming on iPad/YouTube"),
    "1808001": ("feature_request_feedback", False, "apple watch app request"),
    "2783470": ("billing_subscription", False, "promo payment via load (TL) question"),
    "1933357": ("feature_request_feedback", False, "apple watch app request"),
    "960096": ("device_integration", False, "Galaxy s8 + Windows 10 setup context"),
    "2277222": ("other_offtopic", False, "vague mobile quality complaint"),
    "16209": ("device_integration", False, "PS4 clarification"),
    "2807576": ("feature_request_feedback", False, "apple watch availability question"),
    "2605003": ("technical_issue", False, "problem persists on Mac and iPhone"),
    "808334": ("feature_request_feedback", False, "bring back touch preview"),
    "1962699": ("closing_acknowledgement", False, "working now"),
    "850054": ("feature_request_feedback", False, "personalization expectation"),
    "1900368": ("feature_request_feedback", False, "Discover Weekly recommendation drift"),
    "1905161": ("feature_request_feedback", False, "feature praise"),
    "2789423": ("other_offtopic", False, "sarcastic complaint about support; frustration not abuse"),
    "637656": ("other_offtopic", False, "err any ideas? (context only)"),
    "406691": ("feature_request_feedback", False, "feature education/engagement"),
    "2774596": ("other_offtopic", False, "please reply to DM"),
    "2447671": ("feature_request_feedback", False, "bring back 3D touch preview"),
    "1796591": ("content_library", False, "kid channel playing wrong content"),
    "2643174": ("other_offtopic", False, "show some love (no issue)"),
    "2251540": ("feature_request_feedback", False, "iPhone X support"),
    "1500874": ("feature_request_feedback", False, "downvote discover tracks"),
    "1474905": ("closing_acknowledgement", False, "thanks for taking it seriously"),
    "2211014": ("closing_acknowledgement", False, "voted (done)"),
    "2806766": ("other_offtopic", False, "DM nudge"),
    "1315618": ("closing_acknowledgement", False, "thanks"),
    "2144252": ("technical_issue", False, "error persists across browsers"),
    "2823506": ("other_offtopic", False, "company history question (off-topic)"),
    "2916530": ("content_library", False, "BTS album availability"),
    "1788392": ("feature_request_feedback", False, "ads alongside music complaint"),
    "1515482": ("feature_request_feedback", False, "quick suggestion"),
    "1934843": ("account_admin", False, "gender not synced from Facebook"),
    "2786591": ("other_offtopic", False, "3 years in a row (context)"),
    "619686": ("other_offtopic", False, "notice request"),
    "2284931": ("other_offtopic", False, "I make beats (promo)"),
    "1682043": ("feature_request_feedback", False, "iPhone X optimization"),
    "2043164": ("other_offtopic", False, "will it work? (ambiguous)"),
    "429213": ("feature_request_feedback", False, "no visual selected indicator"),
    "759467": ("feature_request_feedback", False, "bring back in-app messaging"),
    "632031": ("technical_issue", False, "vague 'trouble with Spotify'"),
    "1915270": ("content_library", False, "what is Stranger Things mode"),
    "1699324": ("other_offtopic", False, "DM request"),
    "1395881": ("other_offtopic", False, "joking plea (not a threat)"),
    "1644817": ("account_access", False, "needs account help; DM'd earlier"),
    "1078973": ("other_offtopic", True, "abusive gesture towards support"),
    "2234724": ("feature_request_feedback", False, "iPhone X unsupported complaint"),
    "2550449": ("feature_request_feedback", False, "would like a feature"),
    "1050745": ("billing_subscription", False, "family invite not accepted"),
    "1913460": ("technical_issue", False, "lock-screen not showing music"),
    "185156": ("billing_subscription", False, "upgrade attempt error"),
    "2473670": ("other_offtopic", False, "additional screenshot (no text)"),
    "2780853": ("feature_request_feedback", False, "4 commercials in a row"),
    "1288447": ("technical_issue", False, "cannot rearrange after update"),
    "724359": ("technical_issue", False, "web player stalling"),
    "875182": ("device_integration", False, "audio drops during Chromecast casting"),
    "577397": ("account_admin", False, "sales data question from aggregator dashboard"),
    "2780842": ("technical_issue", False, "weird database activity"),
    "2919379": ("technical_issue", False, "error when searching artists"),
    "2161294": ("account_access", False, "keeps logging out; re-downloads"),
    "1788065": ("device_integration", False, "same network clarification"),
    "1495683": ("technical_issue", False, "crashes weekly (frustration, not abusive)"),
    "848534": ("technical_issue", False, "suggestions stop; all data sources"),
    "2412661": ("closing_acknowledgement", False, "praise for support"),
    "2065702": ("device_integration", True, "neighbors can change music on shared wifi - unauthorized control via Connect"),
    "2353930": ("feature_request_feedback", False, "offline library search"),
    "637669": ("technical_issue", False, "keyboard media keys require restart"),
    "89484": ("technical_issue", False, "it's not working (context)"),
    "64345": ("account_access", False, "Facebook login broken"),
    "1034388": ("device_integration", False, "Google Home trigger question"),
    "859888": ("technical_issue", False, "web player down for many users"),
    "2039424": ("technical_issue", False, "offline albums re-download weekly"),
    "2756632": ("account_access", True, "possible account use - unknown Spotify Connect notifications"),
    "173654": ("feature_request_feedback", False, "download limit complaint"),
    "2657401": ("technical_issue", False, "iOS volume control broken on connect device"),
    "2776188": ("technical_issue", False, "playback pauses/skips while walking"),
    "2626482": ("device_integration", False, "Xbox One: playing bar but no sound"),
    "104122": ("account_access", False, "CSRF token login error"),
}


def main() -> None:
    cands = [json.loads(l) for l in open("eval/golden_candidates.jsonl")]
    missing = [c["id"] for c in cands if c["id"] not in GOLD]
    assert not missing, f"unlabelled: {missing}"
    extra = set(GOLD) - {c["id"] for c in cands}
    assert not extra, f"labels without candidates: {extra}"

    with open("eval/golden_set.jsonl", "w") as f:
        for c in cands:
            intent, esc, reason = GOLD[c["id"]]
            rec = {
                "id": c["id"],
                "message": c["message"],
                "gold_intent": intent,
                "gold_escalate": esc,
                "gold_escalation_reason": reason if esc else "",
                "bucket": c["bucket"],
            }
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")
    print("wrote eval/golden_set.jsonl with", len(cands), "examples")


if __name__ == "__main__":
    main()